services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=bookstore_db
      - DB_PORT=5432
    depends_on:
      - postgres
    command: /app/main

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookstore_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: