basePath: /api/v1
definitions:
  authors.Author:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  books.Book:
    properties:
      author:
        $ref: '#/definitions/authors.Author'
      category:
        $ref: '#/definitions/categories.Category'
      id:
        type: integer
      synopsis:
        type: string
      title:
        type: string
    type: object
  bookstore_api_internal_books_controller.CreateBookInput:
    properties:
      author:
        properties:
          name:
            type: string
        required:
        - name
        type: object
      category:
        properties:
          name:
            type: string
        required:
        - name
        type: object
      synopsis:
        type: string
      title:
        type: string
    required:
    - author
    - category
    - synopsis
    - title
    type: object
  categories.Category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: An CRUD to manage a bookstore.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Bookstore API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/books.Book'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Create a new book
      parameters:
      - description: Book information
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/bookstore_api_internal_books_controller.CreateBookInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/books.Book'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Create a new book
      tags:
      - books
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a book by its ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a book by its ID
      tags:
      - books
    get:
      consumes:
      - application/json
      description: Get a book by its ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/books.Book'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get a book by its ID
      tags:
      - books
    put:
      consumes:
      - application/json
      description: Update a book by its ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      - description: Book information
        in: body
        name: input
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/books.Book'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update a book by its ID
      tags:
      - books
swagger: "2.0"
